version: '3'
services:
  caddy:
    image: caddy
    ports:
      - 80:80
    volumes:
     - ./caddy:/data
     - ./Caddyfile:/etc/caddy/Caddyfile
     - ./app:/var/www/html:ro
  php:
    build:
      context: .
      dockerfile: php-Dockerfile
    volumes:
      - ./app:/var/www/html:ro      
  mail: 
    image: boky/postfix
    environment:
      - ALLOWED_SENDER_DOMAINS=group.lt
      - POSTFIX_always_add_missing_headers=yes
      - HOSTNAME=fqdn.group.lt # set to the hostname of the server
      
